// <auto-generated />
namespace Vueling.DataAccess.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_db));
        
        string IMigrationMetadata.Id
        {
            get { return "201806272200531_initial_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
